# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messageservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14messageservice.proto\"%\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"L\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\"\"\n\x0eMessageRequest\x12\x10\n\x08receiver\x18\x01 \x01(\t\"-\n\x0fMessageResponse\x12\x1a\n\x08messages\x18\x01 \x03(\x0b\x32\x08.Message2h\n\x0eMessageService\x12\"\n\x0bSendMessage\x12\x08.Message\x1a\x07.Status\"\x00\x12\x32\n\x0bGetMessages\x12\x0f.MessageRequest\x1a\x10.MessageResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messageservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=24
  _STATUS._serialized_end=61
  _MESSAGE._serialized_start=63
  _MESSAGE._serialized_end=139
  _MESSAGEREQUEST._serialized_start=141
  _MESSAGEREQUEST._serialized_end=175
  _MESSAGERESPONSE._serialized_start=177
  _MESSAGERESPONSE._serialized_end=222
  _MESSAGESERVICE._serialized_start=224
  _MESSAGESERVICE._serialized_end=328
# @@protoc_insertion_point(module_scope)
