# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messageservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14messageservice.proto\"#\n\x0fUsernameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"@\n\x0eMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"\'\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\"(\n\x12StatusCodeResponse\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\"5\n\x0eSearchResponse\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x0f\n\x07results\x18\x02 \x03(\t\"?\n\rLoginResponse\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x1a\n\x08messages\x18\x02 \x03(\x0b\x32\x08.Message2\xe7\x02\n\x0eMessageService\x12\x33\n\x08Register\x12\x10.UsernameRequest\x1a\x13.StatusCodeResponse\"\x00\x12\x30\n\x05Login\x12\x10.UsernameRequest\x1a\x13.StatusCodeResponse\"\x00\x12+\n\tSubscribe\x12\x10.UsernameRequest\x1a\x08.Message\"\x00\x30\x01\x12+\n\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\"\x00\x12.\n\x04Send\x12\x0f.MessageRequest\x1a\x13.StatusCodeResponse\"\x00\x12\x31\n\x06Logout\x12\x10.UsernameRequest\x1a\x13.StatusCodeResponse\"\x00\x12\x31\n\x06\x44\x65lete\x12\x10.UsernameRequest\x1a\x13.StatusCodeResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messageservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERNAMEREQUEST._serialized_start=24
  _USERNAMEREQUEST._serialized_end=59
  _SEARCHREQUEST._serialized_start=61
  _SEARCHREQUEST._serialized_end=91
  _MESSAGEREQUEST._serialized_start=93
  _MESSAGEREQUEST._serialized_end=157
  _MESSAGE._serialized_start=159
  _MESSAGE._serialized_end=198
  _STATUSCODERESPONSE._serialized_start=200
  _STATUSCODERESPONSE._serialized_end=240
  _SEARCHRESPONSE._serialized_start=242
  _SEARCHRESPONSE._serialized_end=295
  _LOGINRESPONSE._serialized_start=297
  _LOGINRESPONSE._serialized_end=360
  _MESSAGESERVICE._serialized_start=363
  _MESSAGESERVICE._serialized_end=722
# @@protoc_insertion_point(module_scope)
